services:
  _defaults:
    autoconfigure: true
  PresProg\ContaoResizeOnUploadBundle\EventListener\FileUploadListener:
    arguments:
      - '@contao.framework'
      - '@PresProg\ContaoResizeOnUploadBundle\ImageResizer'
