services:

    _defaults:
        autoconfigure: true

    PresProg\ResizeOnUpload\Command\GenerateMissingThumbnailsCommand:
        arguments:
            - '@contao.framework'
            - '@PresProg\ResizeOnUpload\ImageResizer'
