services:

    PresProg\ResizeOnUpload\EventListener\FileUploadListener:
        arguments:
            - '@contao.framework'
            - '@PresProg\ResizeOnUpload\ImageResizer'

    PresProg\ResizeOnUpload\EventListener\DataContainer\FilesContainer:
        arguments:
            - '@contao.framework'
