services:

  PresProg\ResizeOnBundle\EventListener\FileUploadListener:
    arguments:
      - '@contao.framework'
      - '@PresProg\ResizeOnBundle\ImageResizer'

  PresProg\ContaoResizeOnUpload\EventListener\DataContainer\FilesContainer:
      arguments:
          - '@contao.framework'
