services:

  PresProg\ResizeOnUpload\EventListener\FileUploadListener:
    arguments:
      - '@contao.framework'
      - '@PresProg\ResizeOnUpload\ImageResizer'

  PresProg\ContaoResizeOnUpload\EventListener\DataContainer\FilesContainer:
      arguments:
          - '@contao.framework'
