services:

    PresProg\ResizeOnUpload\ImageResizer:
        arguments:
            - '@contao.framework'
            - '@contao.image.picture_factory'
            - '@contao.image.legacy_resizer'
            - '@logger'
            - '%contao.image.valid_extensions%'
            - '%kernel.project_dir%'
