services:

  PresProg\ResizeOnUpload\ImageResizer:
    arguments:
      - '@contao.framework'
      - '@contao.image.image_factory'
      - '@contao.image.picture_factory'
      - '@logger'
      - '%contao.image.valid_extensions%'
